name: Update AoC Badges 2024
on:
  schedule: # run workflow based on schedule
    - cron: '54 23 1-25 12 *' # from the 1. December till 25. December every day at 11:54pm (avoid load at full hours)
    # - cron: '6 5 * * 0' # Run once every week on Sunday at 5:06am

  workflow_dispatch: # allow to manually start the workflow

# push: (disabled) run on push, be carefull with this setting
# as the workflow should only be triggered at a rate lower than
# 4 times a hour to keep traffic on aoc site low

permissions:
  actions: read
  contents: write

jobs:
  update:
    uses: ./.github/workflows/aoc-badge.yml
    with:
      year: 2024
    secrets:
      AOC_SESSION: ${{ secrets.AOC_SESSION }}
